import { Book } from './book-types';
import fightClub from '../../assets/fightclub.jpeg';
import survivor from '../../assets/survivor.jpeg';
import invisibleMonsters from '../../assets/invisiblemonsters.jpeg';
import choke from '../../assets/choke.png';
import lullaby from '../../assets/lullaby.jpeg';
import diary from '../../assets/diary.jpeg';
import haunted from '../../assets/haunted.jpeg';
import guts from '../../assets/guts.jpeg';
import rant from '../../assets/rant.jpeg';
import misterelegant from '../../assets/misterelegant.jpg';
import snuff from '../../assets/snuff.jpeg';
import pygmy from '../../assets/pygmy.jpeg';
import tellAll from '../../assets/tellall.jpeg';
import knock from '../../assets/knock.jpg';
import damned from '../../assets/damned.jpeg';
import romance from '../../assets/romance.png';
import imremix from '../../assets/imremix.jpeg';
import doomed from '../../assets/doomed.jpeg';
import burntTongues from '../../assets/burnttongues.jpeg';
import beautfulYou from '../../assets/beautifulyou.jpeg';
import makeSomethingUp from '../../assets/makesomethingup.jpeg';
import phoenix from '../../assets/phoenix.jpg';
import zombie from '../../assets/zombie.jpg';
import cannibal from '../../assets/cannibal.jpg';
import bait from '../../assets/bait.jpeg';
import legacy from '../../assets/legacy.png';
import adjustmentDay from '../../assets/adjustmentday.jpeg';
import fugitives from '../../assets/fugitives.jpeg';
import strangerThanFiction from '../../assets/strangerthanfiction.jpeg';
import considerThis from '../../assets/considerthis.png';
import fightClubTwo from '../../assets/fightclub2.jpg';
import fightClubThree from '../../assets/fightclub3.jpg';

export const bookArr: Book[] = [
  {
    title: `Fight Club`,
    released: 1996,
    img: fightClub,
    amazonLink: `https://www.amazon.com/gp/product/B000U0O9FM/ref=dbs_a_def_rwt_hsch_vapi_tkin_p1_i0`,
    goodreadsLink: `https://www.goodreads.com/book/show/36236124-fight-club`,
    darkHorseLink: null,
    description: `Chuck Palahniuk showed himself to be his generation’s most visionary satirist in this, his first book. Fight Club’s estranged narrator leaves his lackluster job when he comes under the thrall of Tyler Durden, an enigmatic young man who holds secret after-hours boxing matches in the basement of bars. There, two men fight "as long as they have to." This is a gloriously original work that exposes the darkness at the core of our modern world.`,
    category: 'novel',
  },
  {
    title: `Survivor`,
    released: 1999,
    img: survivor,
    amazonLink: `https://www.amazon.com/gp/product/B004SOBLIE/ref=dbs_a_def_rwt_bibl_vppi_i6`,
    goodreadsLink: `https://www.goodreads.com/book/show/36236123-survivor`,
    darkHorseLink: null,
    description: `From the author of the underground sensation Fight Club comes this wickedly incisive second novel, a mesmerizing, unnerving, and hilarious vision of cult and post-cult life. [...] Not since Kurt Vonnegut's Mother Night and Jerzy Kosinski's Being There has there been as dark and telling a satire on the wages of fame and the bedrock lunacy of the modern world. Unpredictable, compelling, and unforgettable, Survivor is Chuck Palahniuk at his deadpan peak; and it cements his place as one of the most original writers in fiction today.`,
    category: 'novel',
  },
  {
    title: `Invisible Monsters`,
    released: 1999,
    img: invisibleMonsters,
    amazonLink: `https://www.amazon.com/gp/product/B004SO5SD8/ref=dbs_a_def_rwt_bibl_vppi_i2`,
    goodreadsLink: `https://www.goodreads.com/book/show/36236123-survivor`,
    darkHorseLink: null,
    description: `She's a catwalk model who has everything: a boyfriend, a career, a loyal best friend. But when a sudden motor 'accident' leaves her disfigured and incapable of speech, she goes from being the beautiful centre of attention to being an invisible monster, so hideous that no one will acknowledge she exists.  Enter Brandy Alexander, Queen Supreme, one operation away from being a real woman, who will teach her that reinventing yourself means erasing your past and making up something better, and that salvation hides in the last place you'll ever want to look.`,
    category: 'novel',
  },
  {
    title: `Choke`,
    released: 2001,
    img: choke,
    amazonLink: `https://www.amazon.com/gp/product/B000QCS9NM/ref=dbs_a_def_rwt_hsch_vapi_tkin_p1_i4`,
    goodreadsLink: `https://www.goodreads.com/book/show/29059.Choke`,
    darkHorseLink: null,
    description: `Victor Mancini, a medical-school dropout, is an antihero for our deranged times. Needing to pay elder care for his mother, Victor has devised an ingenious scam: he pretends to choke on pieces of food while dining in upscale restaurants. He then allows himself to be “saved” by fellow patrons who, feeling responsible for Victor’s life, go on to send checks to support him. When he’s not pulling this stunt, Victor cruises sexual addiction recovery workshops for action, visits his addled mom, and spends his days working at a colonial theme park. His creator, Chuck Palahniuk, is the visionary we need and the satirist we deserve.`,
    category: 'novel',
  },
  {
    title: `Lullaby`,
    released: 2002,
    img: lullaby,
    amazonLink: `https://www.amazon.com/gp/product/B0013KAJR0/ref=dbs_a_def_rwt_hsch_vapi_tkin_p1_i10`,
    goodreadsLink: `https://www.goodreads.com/book/show/22206.Lullaby`,
    darkHorseLink: null,
    description: `Carl Streator is a reporter investigating Sudden Infant Death Syndrome for a soft-news feature. After responding to several calls with paramedics, he notices that all the dead children were read the same poem from the same library book the night before they died. It's a 'culling song' - an ancient African spell for euthanising sick or old people. Researching it, he meets a woman who killed her own child with it accidentally. He himself accidentally killed his own wife and child with the same poem twenty years earlier. Together, the man and the woman must find and destroy all copies of this book, and try not to kill every rude sonofabitch that gets in their way. Lullaby is a comedy/drama/tragedy. In that order. It may also be Chuck Palahniuk's best book yet.`,
    category: 'novel',
  },
  {
    title: `Diary`,
    released: 2003,
    img: diary,
    amazonLink: `https://www.amazon.com/gp/product/B000FCK4TA/ref=dbs_a_def_rwt_hsch_vapi_tkin_p1_i11`,
    goodreadsLink: `https://www.goodreads.com/book/show/22284.Diary`,
    darkHorseLink: null,
    description: `Misty Wilmot has had it. Once a promising young artist, she’s now stuck on an island ruined by tourism, drinking too much and working as a waitress in a hotel. Her husband, a contractor, is in a coma after a suicide attempt, but that doesn’t stop his clients from threatening Misty with lawsuits over a series of vile messages they’ve found on the walls of houses he remodeled.  Suddenly, though, Misty finds her artistic talent returning as she begins a period of compulsive painting. Inspired but confused by this burst of creativity, she soon finds herself a pawn in a larger conspiracy that threatens to cost hundreds of lives. What unfolds is a dark, hilarious story from America’s most inventive nihilist, and Palahniuk’s most impressive work to date.`,
    category: 'novel',
  },
  {
    title: `Haunted`,
    released: 2005,
    img: haunted,
    amazonLink: `https://www.amazon.com/gp/product/B000FCK40O/ref=dbs_a_def_rwt_bibl_vppi_i3`,
    goodreadsLink: `https://www.goodreads.com/book/show/22288.Haunted`,
    darkHorseLink: null,
    description: `Haunted is a novel made up of stories: twenty-three of the most horrifying, hilarious, mind-blowing, stomach-churning tales you'll ever encounter.  The stories are told by people who have all answered an ad headlined 'Artists Retreat: Abandon your life for three months'. They are led to believe that here they will leave behind all the distractions of 'real life' that are keeping them from creating the masterpiece that is in them.  But 'here' turns out to be a cavernous and ornate old theater where they are utterly isolated from the outside world - and where heat and power and, most importantly, food are in increasingly short supply. And the more desperate the circumstances become, the more desperate the stories they tell.`,
    category: 'novel//story-compilation',
  },
  {
    title: `Guts [Appears in Haunted]`,
    released: 2005,
    img: guts,
    amazonLink: `https://www.amazon.com/gp/product/B000FCK40O/ref=dbs_a_def_rwt_bibl_vppi_i3`,
    goodreadsLink: `https://www.goodreads.com/book/show/6395833-guts`,
    darkHorseLink: null,
    description: `“People in France have a phrase: "Spirit of the Stairway." In French: Esprit de l'escalier. It means that moment when you find the answer, but it's too late. Say you're at a party and someone insults you. You have to say something. So under pressure, with everybody watching, you say something lame. But the moment you leave the party…  As you start down the stairway, then -- magic. You come up with the perfect thing you should've said. The perfect crippling put-down.  That's the Spirit of the Stairway.  The trouble is even the French don't have a phrase for the stupid things you actually do say under pressure. Those stupid, desperate things you actually think or do.  Some deeds are too low to even get a name. Too low to even get talked about.”`,
    category: 'short fiction',
  },
  {
    title: `Rant`,
    released: 2007,
    img: rant,
    amazonLink: `https://www.amazon.com/gp/product/B00199B2YO/ref=dbs_a_def_rwt_hsch_vapi_tkin_p1_i8`,
    goodreadsLink: `https://www.goodreads.com/book/show/22285.Rant`,
    darkHorseLink: null,
    description: `Buster “Rant” Casey just may be the most efficient serial killer of our time. A high school rebel, Rant Casey escapes from his small town home for the big city where he becomes the leader of an urban demolition derby called Party Crashing. Rant Casey will die a spectacular highway death, after which his friends gather the testimony needed to build an oral history of his short, violent life.`,
    category: 'novel',
  },
  {
    title: `Mister Elegant [in VICE]`,
    released: 2007,
    img: misterelegant,
    amazonLink: null,
    goodreadsLink: `https://www.goodreads.com/book/show/15783331-mister-elegant`,
    darkHorseLink: null,
    description: `A short story about a male stripper who has an 'accident' while dancing on stage (published in Vice Magazine in December 2006).  Don’t ask how I know this, but the next time you think you’re fat, there’s a whole lot worse way you can look.`,
    category: 'short fiction',
  },
  {
    title: `Snuff`,
    released: 2008,
    img: snuff,
    amazonLink: `https://www.amazon.com/gp/product/B0010SEMGY/ref=dbs_a_def_rwt_bibl_vppi_i15`,
    goodreadsLink: `https://www.goodreads.com/book/show/1840511.Snuff`,
    darkHorseLink: null,
    description: `Cassie Wright, porn priestess, intends to cap her legendary career by breaking the world record for serial fornication. On camera. With six hundred men. Snuff unfolds from the perspectives of Mr. 72, Mr. 137, and Mr. 600, who await their turn on camera in a very crowded green room. This wild, lethally funny, and thoroughly researched novel brings the huge yet underacknowledged presence of pornography in contemporary life into the realm of literary fiction at last. Who else but Chuck Palahniuk would dare do such a thing? Who else could do it so well, so unflinchingly, and with such an incendiary (you might say) climax?`,
    category: 'novel',
  },
  {
    title: `Pygmy`,
    released: 2009,
    img: pygmy,
    amazonLink: `https://www.amazon.com/gp/product/B001NLL9IW/ref=dbs_a_def_rwt_bibl_vppi_i12`,
    goodreadsLink: `https://www.goodreads.com/book/show/4601396-pygmy`,
    darkHorseLink: null,
    description: `“Begins here first account of operative me, agent number 67 on arrival Midwestern American airport greater _____ area. Flight _____. Date _____. Priority mission top success to complete. Code name: Operation Havoc.”  Thus speaks Pygmy, one of a handful of young adults from a totalitarian state sent to the United States, disguised as exchange students, to live with typical American families and blend in, all the while planning an unspecified act of massive terrorism. Palahniuk depicts Midwestern life through the eyes of this thoroughly indoctrinated little killer, who hates us with a passion, in this cunning double-edged satire of an American xenophobia that might, in fact, be completely justified. For Pygmy and his fellow operatives are cooking up something big, something truly awful, that will bring this big dumb country and its fat dumb inhabitants to their knees.  It’s a comedy. And a romance.`,
    category: 'novel',
  },
  {
    title: `Tell-All`,
    released: 2010,
    img: tellAll,
    amazonLink: `https://www.amazon.com/gp/product/B0036S4CRK/ref=dbs_a_def_rwt_bibl_vppi_i20`,
    goodreadsLink: `https://www.goodreads.com/book/show/6855294-tell-all`,
    darkHorseLink: null,
    description: `“The hyperactive love child of Page Six and Whatever Happened to Baby Jane? caught in a tawdry love triangle with The Fan. Even Kitty Kelly will blush.  Soaked, nay, marinated in the world of vintage Hollywood, Tell-All is a Sunset Boulevard–inflected homage to Old Hollywood when Bette Davis and Joan Crawford ruled the roost; a veritable Tourette’s syndrome of rat-tat-tat  name-dropping, from the A-list to the Z-list; and a merciless  send-up of Lillian Hellman’s habit of butchering the truth that will have Mary McCarthy cheering from the beyond.  Our Thelma Ritter–ish narrator is Hazie Coogan, who for decades has tended to the outsized needs of Katherine “Miss Kathie”  Kenton—veteran of multiple marriages, career comebacks, and cosmetic surgeries. But danger arrives with gentleman caller Webster Carlton Westward III, who worms his way into Miss Kathie’s heart (and boudoir). Hazie discovers that this bounder has already written a celebrity tell-all memoir foretelling Miss Kathie’s death in a forthcoming Lillian Hellman–penned musical extravaganza; as the body count mounts, Hazie must execute a plan to save Katherine Kenton for her fans—and for posterity.  Tell-All is funny, subversive, and fascinatingly clever. It’s wild, it’s wicked, it’s  boldfaced—it’s vintage Chuck.`,
    category: 'novel',
  },
  {
    title: `Knock Knock [in Playboy]`,
    released: 2010,
    img: knock,
    amazonLink: null,
    goodreadsLink: `https://www.goodreads.com/book/show/18777492-knock-knock`,
    darkHorseLink: null,
    description: `Chuck Palahniuk's hilarious short story Knock-Knock, is featured in the December 2010 issue of Playboy. The story “Knock Knock” is about a boy who grows up with his dad always telling these horrible jokes.  Who could guess "knock-knock" jokes and bad humor could be so entertaining and so messed-up.`,
    category: 'short fiction',
  },
  {
    title: `Damned`,
    released: 2011,
    img: damned,
    amazonLink: `https://www.amazon.com/gp/product/B004KPM1LM/ref=dbs_a_def_rwt_bibl_vppi_i9`,
    goodreadsLink: `https://www.goodreads.com/book/show/9912994-damned`,
    darkHorseLink: null,
    description: `Madison, a thirteen year old girl, finds herself in Hell, unsure of why she will be there for all eternity, but tries to make the best of it.  The author described the novel as "if The Shawshank Redemption had a baby by The Lovely Bones and it was raised by Judy Blume." And "it's kind of like The Breakfast Club set in Hell."`,
    category: 'novel',
  },
  {
    title: `Romance [in Playboy]`,
    released: 2011,
    img: romance,
    amazonLink: null,
    goodreadsLink: `https://www.goodreads.com/book/show/15758720-romance`,
    darkHorseLink: null,
    description: `A short story, read by Chuck himself and available in audio exclusively from Blackstone.  Originally published in Playboy magazine, “Romance” is a twisted love story like only Chuck could tell.  "(...) and then it turned out it wasn't the pineapple or the self-discipline because she found out she really had cancer, but she slimmed down to wearing a bitchin' hot size two before she died."`,
    category: 'short fiction',
  },
  {
    title: `Invisible Monsters Remix`,
    released: 2012,
    img: imremix,
    amazonLink: `https://www.amazon.com/gp/product/B007HXF5GM/ref=dbs_a_def_rwt_hsch_vapi_tkin_p2_i9`,
    goodreadsLink: `https://www.goodreads.com/book/show/12813565-invisible-monsters-remix?from_search=true&from_srp=true&qid=GrLzjd85ou&rank=1`,
    darkHorseLink: null,
    description: `Injected with new material and special design elements, Invisible Monsters Remix fulfills Chuck Palahniuk’s original vision for his 1999 novel, turning a daring satire on beauty and the fashion industry into an even more wildly unique reading experience. Palahniuk’s fashion-model protagonist has it all—boyfriend, career, loyal best friend—until an accident destroys her face, her ability to speak, and her self-esteem. Enter Brandy Alexander, Queen Supreme, one operation away from becoming a bona-fide woman. Laced in are new chapters of memoir and further scenes with the book’s characters. Readers will jump between chapters, reread the book to understand the dissolve between fiction and fact, and decipher the playful book design, embarking on a ride they’ll never forget.`,
    category: 'novel',
  },
  {
    title: `Doomed`,
    released: 2013,
    img: doomed,
    amazonLink: `https://www.amazon.com/gp/product/B00CCPIJ6I/ref=dbs_a_def_rwt_bibl_vppi_i19`,
    goodreadsLink: `https://www.goodreads.com/book/show/17262208-doomed`,
    darkHorseLink: null,
    description: `Madison Spencer, the liveliest and snarkiest dead girl in the universe, continues the afterlife adventure begun in Chuck Palahniuk’s bestseller Damned. Just as that novel brought us a brilliant Hell that only he could imagine, Doomed is a dark and twisted apocalyptic vision from this provocative storyteller.  The bestselling Damned chronicled Madison’s journey across the unspeakable (and really gross) landscape of the afterlife to confront the Devil himself. But her story isn’t over yet. In a series of electronic dispatches from the Great Beyond, Doomed describes the ultimate showdown between Good and Evil.`,
    category: 'novel',
  },
  {
    title: `Phoenix [Kindle Exclusive]`,
    released: 2013,
    img: phoenix,
    amazonLink: null,
    goodreadsLink: `https://www.goodreads.com/book/show/17380711-phoenix`,
    darkHorseLink: null,
    description: `Rachel married Ted because he was uncomplicated and loyal. But he was also devoted to his wretched house (done up in black granite, black appliances, even black dishware) and his first love, an old, flatulent cat named Belinda Carlisle. Once Rachel becomes pregnant, Ted reluctantly agrees to move and give up the cat. But the house doesn't sell, and Belinda Carlisle still haunts their home: every day the creature becomes fatter and more malodorous. When the house burns to the ground in a freak conflagration and the couple's daughter, April, is born blind soon thereafter, the marriage is never the same again. Only on a business trip three years later does Rachel begin to reckon with the damage.`,
    category: 'short fiction',
  },
  {
    title: `Zombie [in Playboy]`,
    released: 2013,
    img: zombie,
    amazonLink: null,
    goodreadsLink: `https://www.goodreads.com/book/show/18853743-zombie`,
    darkHorseLink: null,
    description: `In 'Zombies', the absurdity of both life and death are on full display as the best and brightest of a high school prep school become tragically addicted to the latest drug craze - electronic shocks from cardiac defibrillators.  Funny, caustic, bizarre, poignant - this story represents everything listeners have come to love and expect from Chuck Palahniuk.`,
    category: 'short fiction',
  },
  {
    title: `Cannibal [in Playboy]`,
    released: 2013,
    img: cannibal,
    amazonLink: null,
    goodreadsLink: `https://www.goodreads.com/book/show/17856443-cannibal`,
    darkHorseLink: null,
    description: `His talent made him popular with a certain kind of girl.  "We'll take drug addiction and we'll take JPEGs of the world instead of the world, MP3s instead of music, and we'll trade real life for sitting at a keyboard. We'll spot you happiness and we'll spot you humanity, and we'll sacrifice mercy just so long as you keep Cannibal at bay."`,
    category: 'short fiction',
  },
  {
    title: `Burnt Tongues [Editor]`,
    released: 2014,
    img: burntTongues,
    amazonLink: `https://www.amazon.com/gp/product/1605427349/ref=dbs_a_def_rwt_bibl_vppi_i64`,
    goodreadsLink: `https://www.goodreads.com/book/show/20344952-burnt-tongues`,
    darkHorseLink: null,
    description: `Transgressive fiction authors write stories some are afraid to tell. Stories with taboo subjects, unique voices, shocking images—nothing safe or dry.  Burnt Tongues is a collection of transgressive stories selected by a rigorous nomination and vetting process and hand-selected by Chuck Palahniuk, author of Fight Club, as the best of The Cult workshop, his official fan website.  These stories run the gamut from horrific and fantastic to humorous and touching, but each leaves a lasting impression.  Some may say even a scar.`,
    category: 'story-compilation',
  },
  {
    title: `Beautiful You`,
    released: 2014,
    img: beautfulYou,
    amazonLink: `https://www.amazon.com/gp/product/B00JYWUHDA/ref=dbs_a_def_rwt_bibl_vppi_i16`,
    goodreadsLink: `https://www.goodreads.com/book/show/19523454-beautiful-you`,
    darkHorseLink: null,
    description: `Penny Harrigan is a low-level associate in a big Manhattan law firm with an apartment in Queens and no love life at all. So it comes as a great shock when she finds herself invited to dinner by one C. Linus Maxwell, a software mega-billionaire and lover of the most gorgeous and accomplished women on earth. After dining at Manhattan's most exclusive restaurant, he whisks Penny off to a hotel suite in Paris, where he proceeds, notebook in hand, to bring her to previously undreamed-of heights of gratification for days on end. What's not to like?`,
    category: 'novel',
  },
  {
    title: `Make Something Up`,
    released: 2015,
    img: makeSomethingUp,
    amazonLink: `https://www.amazon.com/gp/product/1101971967/ref=dbs_a_def_rwt_bibl_vppi_i85`,
    goodreadsLink: `https://www.goodreads.com/book/show/22822857-make-something-up`,
    darkHorseLink: null,
    description: `Stories you'll never forget—just try—from literature's favorite transgressive author.  Funny, caustic, bizarre, poignant; these stories represent everything readers have come to love and expect from Chuck Palahniuk. They have all the impact of a sharp blow to the solar plexus, with considerable collateral damage to the funny bone.`,
    category: 'story-compilation',
  },
  {
    title: `Bait`,
    released: 2016,
    img: bait,
    amazonLink: `https://www.amazon.com/gp/product/1506703119/ref=dbs_a_def_rwt_bibl_vppi_i54`,
    goodreadsLink: `https://www.goodreads.com/book/show/30641072-bait`,
    darkHorseLink: null,
    description: `New York Times best-selling novelist Chuck Palahniuk (Fight Club, Lullaby) presents the ultimate coloring book for adults with this new collection of short stories, illustrated by some of the most exciting artists in comics and beyond.`,
    category: 'story-compilation',
  },
  {
    title: `Legacy`,
    released: 2017,
    img: legacy,
    amazonLink: `https://www.amazon.com/gp/product/1506706150/ref=dbs_a_def_rwt_bibl_vppi_i55`,
    goodreadsLink: `https://www.goodreads.com/book/show/35517083-legacy`,
    darkHorseLink: null,
    description: `An amoral investment banker named Vincent receives an inheritance promising immortality. Unfortunately for Vincent, to obtain immortality he has to contend with a flame-retardant stripper, a ruthless stalker, and a bloodthirsty horde of aspiring immortals dead set in their desire to separate Vincent from his destiny.`,
    category: 'novel',
  },
  {
    title: `Adjustment Day`,
    released: 2019,
    img: adjustmentDay,
    amazonLink: `https://www.amazon.com/gp/product/B0777T1T89/ref=dbs_a_def_rwt_bibl_vppi_i5`,
    goodreadsLink: `https://www.goodreads.com/book/show/36349731-adjustment-day?from_search=true&from_srp=true&qid=yIx25IATWP&rank=1`,
    darkHorseLink: null,
    description: `People pass the word only to those they trust most: Adjustment Day is coming. They’ve been reading a mysterious book and memorizing its directives. They are ready for the reckoning.  When Adjustment Day arrives, it fearlessly makes real the logical conclusion of every separatist fantasy, alternative fact, and conspiracy theory lurking in the American psyche.`,
    category: 'novel',
  },
  {
    title: `Fugitive and Refugees`,
    released: 2003,
    img: fugitives,
    amazonLink: `https://www.amazon.com/gp/product/B000XUBE8O/ref=dbs_a_def_rwt_bibl_vppi_i22`,
    goodreadsLink: `https://www.goodreads.com/book/show/22289.Fugitives_and_Refugees`,
    darkHorseLink: null,
    description: `Want to know where Chuck Palahniuk's tonsils currently reside?  Been looking for a naked mannequin to hide in your kitchen cabinets?  Curious about Chuck's debut in an MTV music video?  What goes on at the Scum Center?  How do you get to the Apocalypse Café?  In the closest thing he may ever write to an autobiography, Chuck Palahniuk provides answers to all these questions and more as he takes you through the streets, sewers, and local haunts of Portland, Oregon.`,
    category: 'non-fiction',
  },
  {
    title: `Stranger than Fiction`,
    released: 2004,
    img: strangerThanFiction,
    amazonLink: `https://www.amazon.com/gp/product/B000FCK4T0/ref=dbs_a_def_rwt_bibl_vppi_i18`,
    goodreadsLink: `https://www.goodreads.com/book/show/3717.Stranger_than_Fiction?ac=1&from_search=true&qid=zmx0owQKQH&rank=1`,
    darkHorseLink: null,
    description: `Chuck Palahniuk’s world has always been, well, different from yours and mine. In his first collection of nonfiction, Chuck Palahniuk brings us into this world, and gives us a glimpse of what inspires his fiction.At the Rock Creek Lodge Testicle Festival in Missoula, Montana, average people perform public sex acts on an outdoor stage. In a mansion once occupied by The Rolling Stones, Marilyn Manson reads his own Tarot cards and talks sweetly to his beautiful actress girlfriend. Across the country, men build their own full-size castles and rocketships that will send them into space. Palahniuk himself experiments with steroids, works on an assembly line by day and as a hospice volunteer by night, and experiences the brutal murder of his father by a white supremacist. With this new direction, Chuck Palahniuk has proven he can do anything.`,
    category: 'non-fiction',
  },
  {
    title: `Consider This`,
    released: 2020,
    img: considerThis,
    amazonLink: `https://www.amazon.com/gp/product/B07SHSG173/ref=dbs_a_def_rwt_bibl_vppi_i1`,
    goodreadsLink: `https://www.goodreads.com/book/show/46210749-consider-this`,
    darkHorseLink: null,
    description: `In this spellbinding blend of memoir and insight, bestselling author Chuck Palahniuk shares stories and generous advice on what makes writing powerful and what makes for powerful writing.  With advice grounded in years of careful study and a keenly observed life, Palahniuk combines practical advice and concrete examples from beloved classics, his own books, and a"kitchen-table MFA" culled from an evolving circle of beloved authors and artists, with anecdotes, postcards from the road, and much more.`,
    category: 'non-fiction',
  },
  {
    title: `Fight Club 2`,
    released: 2015,
    img: fightClubTwo,
    amazonLink: `https://www.amazon.com/gp/product/B01668BX8W/ref=dbs_a_def_rwt_bibl_vppi_i24`,
    goodreadsLink: `https://www.goodreads.com/book/show/51807884-fight-club-3`,
    darkHorseLink: `https://www.darkhorse.com/Books/27-009/Fight-Club-2-HC`,
    description: `Ten years after starting Project Mayhem, he lives a mundane life. A kid, a wife. Pills to keep his destiny at bay. But it won’t last long—the wife has seen to that. He’s back where he started, but this go-round he’s got more at stake than his own life. The time has arrived.`,
    category: 'graphic novel',
  },
  {
    title: `Fight Club 3`,
    released: 2019,
    img: fightClubThree,
    amazonLink: `https://www.amazon.com/gp/product/B07VF1TTK5/ref=dbs_a_def_rwt_bibl_vppi_i14`,
    goodreadsLink: `https://www.goodreads.com/book/show/25614994-fight-club-2`,
    darkHorseLink: `https://www.darkhorse.com/Books/3003-734/Fight-Club-3-HC`,
    description: `A new movement has replaced Project Mayhem, and even Tyler Durden doesn't know how to play by these rules.  Marla Singer is about to deliver her second child, but the daddy isn't her husband--it's Tyler, who's very invested in his heir, and the world he'll inherit, as Die Off Industries plots to fine-tune mankind.`,
    category: 'graphic novel',
  },
];
